### ISSUE TITLE
Why can't I dunk?

### ISSUE THREAD

**Issue by contolini** [khandelwal/AskShashank#1]
I was shooting hoops with some friends and they have mad skillz. Why don't I have mad skillz on the court? How can I learn to dunk?

**Comment by theresaanna** [comment]
![image](https://cloud.githubusercontent.com/assets/126935/3893532/a83e3ba4-223b-11e4-9cfd-15f908e08da7.png)

**Comment by khandelwal** [comment]
I have done some extensive research on this topic. I read many articles on how to dunk better. A lot of them had to do with how to appropriately dunk a piece of biscotti into your non-fat, soy, double shot mocha vanilla latte. This is a passionate topic amongst lovers of coffee and biscotti. In fact, there are certain people you can't be friends with until you've learned how to dunk your biscotti correctly. I spent roughly 30 hours researching how to dunk biscotti then realized that we were talking about your hopes and dreams - not mine. 

www.wikihow.com is a reliable source of information on how to do the sports better. So, I looked up how to dunk on there. The ad on the page says "Meet Singles into Cycling", so I'm thinking that maybe it's just better if you ride bicycles. You can meet singles that way. Apparently you can't meet singles playing hoops. I don't know how to explain this social phenomenon. 

Anyway, here are the things you should do:
1. Dribble
2. Use a smaller ball
3. Work on your ball handling
4. Land correctly
5. Practice dunking on a shorter rim
6. Invest in a good pair of shoes
7. Be persistent
8. Increase your vertical leap. 
9. Learn about plyometrics
10. Work on your flexibility
11. Start running stairs
12. Practice jumping at the court

Let me know how it works out. Or if you meet singles cycling.
