### ISSUE TITLE
HOW WAS YOUR WEEKEND?

### ISSUE THREAD

**Issue by stephanieosan** [khandelwal/AskShashank#11]
We miss you.

**Comment by khandelwal** [comment]
Let's see. On Wednesday, we met up with one of my wife's friends from college and ate tapas at Jaleo and got gelato afterwards from Pitango Gelato. Pitango is basically some of the best gelato I've ever had. Mmm. So tasty. When you are next in town, we'll eat at DC Taco and then go for Pitango. 

On Saturday we were at home. I finally got around to putting up photographs from Machu Picchu and Capadoccia on the wall. The rest of the day was spent just hanging around at home, decompressing from the last job. In the evening we went to go watch the 100 Foot Journey (it's pretty excellent - go watch it). 

Sunday we wandered around one of the DC neighborhoods, and ate some tasty falafel.

**Comment by khandelwal** [comment]
How was your weekend @stephanieosan?

**Comment by stephanieosan** [comment]
I had a quiet weekend. 

Friday was closing night of my play, which was fun, and a relief, and followed by late-night beer and snacks with the cast. 

Saturday and Sunday were days spent recovering. At least for me, whenever a major project (especially creative projects) that you've been putting lots of energy into wraps up, there's always an adrenaline-let-down for the first few days after. I'm completely devoid of energy and wiped out. A design school friend used to call it post-project-depression. 

So, that was my weekend. Necessarily quiet. 

We also did a lot of packing—we're moving into our new house right after labor day! (Haven't closed yet, we're renting it for a few weeks until we close.)

**Comment by khandelwal** [comment]
Are there photographs from your play? I'd love to see some! Attach here!

**Comment by jehlers** [comment]
@stephanieosan that's a fast move! Good luck!!!!!

**Comment by stephanieosan** [comment]
@khandelwal HOW WAS YOUR LONG WEEKEND?
