### ISSUE TITLE
How do I IM on my new work laptop?

### ISSUE THREAD

**Issue by theresaanna** [khandelwal/AskShashank#12]
I want to be able to sign into Gchat on a non-GSA account so I can chat with lovely folks like @iuloshi. I can't seem to get the Hangouts plugin to work. It seems to only want to connect to my logged in account, which is my GSA account, and that account doesn't work with the plugin anyway. I was hoping to be able to sign into a different account with the plugin.

Anyway, since you're in DC with the majority of folks, have you seen anyone who seems to have made this work successfully?

**Comment by khandelwal** [comment]
Hello...hello. Yes, yes. I am Rajeev from Calcutta. I will be helping you with your problems today. Will you please to restart your computer now? It still not working? Did you check power cable? Please restart your computer now. 

Do I look like Tech Support to you? Never mind, don't answer that. 

@NoahKunin probably has the answer to your question. He seems like the sort of person who would.

**Comment by theresaanna** [comment]
Way to make me feel bad. THATS NOT WHAT I MEANT.

**Comment by theresaanna** [comment]
So, I have an imperfect solution. I'm opening Gmail in Safari and popping IM windows free so I can just minimize my email. I'd rather not open my whole personal email on my work machine, but that's the best I've got for now. So folks can IM me at theresasumma@gmail.com!

**Comment by jpyuda** [comment]
Or you can just install Adium.

**Comment by theresaanna** [comment]
For real, it didn't occur to me at this point that I'd be able to install things. Also blah, Adium.
