### ISSUE TITLE
Where to buy a great tie

### ISSUE THREAD

**Issue by stephanieosan** [khandelwal/AskShashank#13]
Hello stylish people of the internet,

I am getting married and would like to buy my beau a tie for the wedding. 

I have a few requirements for said wedding tie:
- Need to buy on the internet (I live in a men's clothing desert!)
- Prefer interesting patterns
- Prefer handmade things, but not required
- Needs to be lovely
- Needs to not be ugly
- Needs to not be boring

Although I hear the merits of bow ties, I don't think that will be the best look for my dude. He wanted to wear a bolo tie, but I suspect bolo ties and three-piece suits aren't meant to be. 

@jpyuda If you're not comfortable sharing your top-secret tie advice here, I will email you.

**Comment by theresaanna** [comment]
Are there any particular colors you have in mind? Does it matter if it matches an overall aesthetic?

**Comment by stephanieosan** [comment]
Hmmm. 

Colors that come to mind: turquoise, greens (esp blue-greens). He'd also look good in bright blues. Also open to yellow/oranges. No red. 

It doesn't need to match any overall aesthetic. Not sure that we have an overall aesthetic :)

Got any ideas?

**Comment by khandelwal** [comment]
I think this is a great, defining moment in your relationship with your dude. Sure he loves you. Sure you've agreed to marry each other. I'm even certain that there are vows involved that lean towards the sentiments of 'forever'. But, let me ask you this: will he wear a tie with your face on it? 

If the answer is yes, then obviously this is the only choice that makes sense:
http://photo.walgreens.com/walgreens/photo-gifts/product=necktie-twosides

Ask him that question IMMEDIATELY and report back. If the answer is 'no', well then. I'll be sitting you two down for a bit of a chat won't I? 

In case it comes up, here are the benefits of a Stephanie Neck Tie: 
- Can be ordered on the internets
- Interesting pattern
- Clearly lovely 
- Obviously not ugly
- How could it possibly be boring? 

Note 1: You _can_ wear a bolo tie with a three piece suit. See: http://static.entertainmentwise.com/photos/Image/wenn20461094.jpg 
I've not met dude. I'm going to assume he's at least as dapper as that. 

Note 2: If for some strange reason the photo tie is not to _your_ liking (I can't imagine that, can you?), you could consider making him a tie: http://www.craftsy.com/pattern/sewing/clothing/free-mens-necktie-with-tutorial/93242. That should agree with the settler in you.

**Comment by stephanieosan** [comment]
W-O-W. This is the most incredible AskShashank I've been involved in.

**Comment by theresaanna** [comment]
:clap:

**Comment by stephanieosan** [comment]
I would like to report back that he did end up wearing a bow tie, so bow ties lovers rejoice!

**Comment by jehlers** [comment]
Pics for proof?

**Comment by stephanieosan** [comment]
##### This squirrely dude married us:

![20141018_164330](https://cloud.githubusercontent.com/assets/6433178/4863688/a8a1303c-6116-11e4-9bf8-c4fa652a01da.jpg)

##### We did it:

![img_2356](https://cloud.githubusercontent.com/assets/6433178/4863693/b3aed024-6116-11e4-8328-3293d5dea848.JPG)

##### There was dancing:

![img_2366](https://cloud.githubusercontent.com/assets/6433178/4863705/c8ee39fc-6116-11e4-9cfc-98ca25eb8013.JPG)

##### One of our best friends lives in Dhaka, and she commissioned this painting of us as a wedding gift:

![imag0146](https://cloud.githubusercontent.com/assets/6433178/4863722/e4d46c68-6116-11e4-87b7-8c64c7f9f89b.jpg)
She did not ask the artist to add the weapons or alien coloring, he did that of his own accord.

**Comment by jehlers** [comment]
You have good friends! And this made my day :D

**Comment by stephanieosan** [comment]
We missed you! <3 

I also hope there are some compromising photos of Ben Guhin dancing somewhere, on someone's camera, but I haven't seen them yet.
