### ISSUE TITLE
What should I have for lunch today?

### ISSUE THREAD

**Issue by iuloshi** [khandelwal/AskShashank#23]
:hamburger: :ramen: :pizza: :fried_shrimp: :apple: :sushi: ?

**Comment by jehlers** [comment]
:sushi: :exclamation:

**Comment by khandelwal** [comment]
Looks like I'm late to this. I hope you had :sushi:.

**Comment by khandelwal** [comment]
:sushi: :fish: :fishing_pole_and_fish: :tropical_fish:

**Comment by theresaanna** [comment]
I'm late for lunch but I can make recommendations for snacktime! :pineapple: :apple: :green_apple: :chocolate_bar: :banana: :strawberry: :cherries:

**Comment by khandelwal** [comment]
I am worried that @iuloshi didn't eat any lunch and has collapsed, as we haven't heard from her.

**Comment by iuloshi** [comment]
I only eat if @khandelwal tells me to.
