### ISSUE TITLE
Why aren't you listed as an 18F employee?

### ISSUE THREAD

**Issue by stephanieosan** [khandelwal/AskShashank#29]
There's no cute circular picture of you on 18F's website. 

![screen shot 2014-11-21 at 1 06 54 pm](https://cloud.githubusercontent.com/assets/6433178/5146930/5da1ccc6-717f-11e4-860a-a47869686bca.png)

Is this some kind of conspiracy? Do you not actually work there? Do you really still work at the CFPB and just told me you were quitting because you didn't want to work on my team any more but you're actually still lurking around? What's going on?!

**Comment by khandelwal** [comment]
![shashank-adam-bureaucrats](https://cloud.githubusercontent.com/assets/636752/5147070/7ad6c30e-7180-11e4-93e6-0183875310f7.jpg)

This is a picture this morning of me and Adam at the CFPB HQ building.

**Comment by stephanieosan** [comment]
So it's true... :sob:

**Comment by theresaanna** [comment]
The real answer is that each employee needs to add themselves to the website, and Shashank clearly can't be bothered.

**Comment by jpyuda** [comment]
You have to use the Konami code to see Shashank.

**Comment by khandelwal** [comment]
Actually, the real answer is that I could not find a picture of me that I liked. All the ones I like have Adam in them. Sometimes, I go to wax museums and take selfies with statues of Nicholas Cage to recreate the 'pictures with Adam' effect. People look at me strange. I mean, if you've been to the museum 500 times and only take a picture with Cage it gets a bit suspicious. But whatever. I'd take actual pictures with Adam more frequently, but he lives in Stars Hollow which is rather far away. 

I've succumbed to pressure and added myself to the website. It's in staging now, and you'll see it production I think quite a bit later. I still don't like my picture.

**Comment by iuloshi** [comment]
@khandelwal Wait, does Nicholas Cage work for the government too? That kinda explains those National Treasure movies...

**Comment by ascott1** [comment]
@iuloshi oh no you di'int.

**Comment by khandelwal** [comment]
@stephanieosan I'm now listed. I'm waiting for my life to change in wonderful and amazing ways but it hasn't yet. Turns out being listed on a webpage isn't as exciting as it should be. This reality is making me sad. Help.

**Comment by stephanieosan** [comment]
Oh noooo! 

I will send reinforcements to DC so that your life feels magical and exciting again. 
Expect reinforcements to arrive on approximately January 19th.
